#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rails
Version  : 5.0.0
Release  : 11
URL      : https://rubygems.org/downloads/rails-5.0.0.gem
Source0  : https://rubygems.org/downloads/rails-5.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sprockets-rails

%description
# Welcome to Rails
Rails is a web-application framework that includes everything needed to
create database-backed web applications according to the
[Model-View-Controller (MVC)](http://en.wikipedia.org/wiki/Model-view-controller)
pattern.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rails-5.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-rails.gemspec

%build
export LANG=C
gem build rubygem-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rails-5.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rails-5.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rails-5.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/specifications/rails-5.0.0.gemspec
